# Generated by Django 5.2.6 on 2025-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='logout_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
